/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    eclipse
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.json.json)
    api(libs.org.apache.poi.poi)
    api(libs.com.google.guava.guava)
    api(libs.info.picocli.picocli)
    api(libs.org.slf4j.slf4j.api)
    implementation("org.apache.parquet:parquet-avro:1.10.0")
    implementation("org.apache.hadoop:hadoop-common:3.1.0")
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

group = "com.metatrope"
version = "1.0-SNAPSHOT"
description = "tables"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
